ALTER TABLE projects
DROP COLUMN status;

ALTER TABLE projects
ADD COLUMN ready BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN running BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE projects
ADD CONSTRAINT valid_project_state
CHECK (NOT (running = TRUE AND ready = FALSE));