ALTER TABLE projects
DROP CONSTRAINT IF EXISTS valid_project_state;

ALTER TABLE projects
DROP COLUMN IF EXISTS ready,
DROP COLUMN IF EXISTS running;

ALTER TABLE projects
ADD COLUMN status BOOLEAN NOT NULL DEFAULT FALSE;